# Generated by Django 3.0.8 on 2023-02-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230214_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
