# Generated by Django 3.0.8 on 2023-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230214_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Причина списания')),
            ],
            options={
                'verbose_name': 'Причина списания',
                'verbose_name_plural': 'Причины списания',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='postav',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование компании'),
        ),
    ]
