# Generated by Django 3.0.8 on 2023-02-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_podraz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Подотчетное лицо')),
            ],
            options={
                'verbose_name': 'Подочтетное лицо',
                'verbose_name_plural': 'Подотчетные лица',
                'ordering': ['title'],
            },
        ),
    ]
