# Generated by Django 3.0.8 on 2023-03-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230302_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obct',
            options={'ordering': ['podraz', 'title'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Подотчетное лицо'),
        ),
        migrations.AlterField(
            model_name='nom',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='obct',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='podraz',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='postav',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Причина списания'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper', models.IntegerField(verbose_name='Код операции')),
                ('nomerdoc', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('datadoc', models.DateTimeField(verbose_name='Дата документа')),
                ('total', models.FloatField(default=0, verbose_name='Сумма')),
                ('nds', models.IntegerField(default=20, verbose_name='НДС')),
                ('totalwithnds', models.FloatField(default=0, verbose_name='Сумма с НДС')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')),
                ('idfio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Fio', verbose_name='Подотчет')),
                ('idobject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Obct', verbose_name='Объект')),
                ('idpodraz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Podraz', verbose_name='Подразделение')),
                ('idspis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.Spis', verbose_name='Причина списания')),
                ('postav', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Postav', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-datadoc'],
            },
        ),
    ]
