# Generated by Django 3.0.8 on 2023-03-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230309_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurnal',
            old_name='idfio',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='jurnal',
            old_name='idobject',
            new_name='obct',
        ),
        migrations.RenameField(
            model_name='jurnal',
            old_name='idpodraz',
            new_name='podraz',
        ),
        migrations.RenameField(
            model_name='jurnal',
            old_name='idspis',
            new_name='spis',
        ),
    ]
