# Generated by Django 3.0.8 on 2023-03-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230310_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='nds',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='obct',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='podraz',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='postav',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='spis',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='summa',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='summawithnds',
        ),
    ]
