# Generated by Django 3.0.8 on 2023-03-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20230310_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='fio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.Fio', verbose_name='Подотчет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnal',
            name='nds',
            field=models.IntegerField(default=20, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='obct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.Obct', verbose_name='Объект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnal',
            name='podraz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.Podraz', verbose_name='Подразделение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnal',
            name='postav',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.Postav', verbose_name='Поставщик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurnal',
            name='spis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.Spis', verbose_name='Причина списания'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='summa',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='summawithnds',
            field=models.FloatField(default=0, verbose_name='Сумма с НДС'),
        ),
    ]
