# Generated by Django 3.0.8 on 2023-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20230310_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnaldoc',
            name='kol',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
    ]
