# Generated by Django 3.0.8 on 2023-03-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_jurnaldoc_kol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
