# Generated by Django 3.0.8 on 2023-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20230325_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Подотчетное лицо'),
        ),
        migrations.AlterField(
            model_name='nom',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='obct',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='podraz',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='postav',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Причина списания'),
        ),
    ]
